apiVersion: v1
kind: ServiceAccount
metadata:
  name: vpa-recommender
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpa-recommender
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpa-recommender
  template:
    metadata:
      labels:
        app: vpa-recommender
    spec:
      containers:
      - args:
        - --cpu-histogram-decay-half-life=2h76m
        - --recommendation-margin-fraction=0.9173362
        - --pod-recommendation-min-cpu-millicores=178
        image: k8s.gcr.io/autoscaling/vpa-recommender:0.10.0
        imagePullPolicy: Always
        name: recommender
        ports:
        - containerPort: 8942
          name: prometheus
        resources:
          limits:
            cpu: 200m
            memory: 1000Mi
          requests:
            cpu: 50m
            memory: 500Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: vpa-recommender
