apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-template
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-deployment-template
  template:
    metadata:
      labels:
        app: nginx-deployment-template
    spec:
      containers:
      - name: nginx-container-template 
        image: nginx
        resources:
          requests:
            cpu: "25m"
          limits:
            cpu: "50m"

